### ISSUE TITLE
Inquiry Regarding Purchase of GitHub Username for "Atomic" Social Network

### ISSUE THREAD

**Issue by DevOgabek** [atomic/CNN-TinyImageNet#1]
Hello Atomic,

I hope this message finds you well. My team and I are currently developing a social network named "Atomic," and during our search for the perfect GitHub username, we came across your account.

We are interested in acquiring the username "Atomic" for our project. If you're open to selling the username, we would like to discuss the terms and conditions of the transfer.

Please let us know if this is something you would consider, and if so, kindly provide details on your preferred method of communication for further discussion. We believe that having a consistent username across platforms is crucial for our branding, and we hope to reach a mutually beneficial agreement.

Looking forward to your response.

oavazov014@gmail.com

**Comment by atomic** [comment]
nope
